syntax = "proto3";

package emberfilm.authentication.v1;

import "google/protobuf/timestamp.proto";

service AuthenticationService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc VerifyEmail(VerifyEmailRequest) returns (VerifyEmailResponse);
  rpc AuthenticateWithPassword(AuthenticateWithPasswordRequest) returns (AuthenticationSession);
  rpc RefreshAuthentication(RefreshAuthenticationRequest) returns (AuthenticationSession);
}

message RegisterRequest {
  string name = 1;
  string email = 2;
  string password = 3;
}

message RegisterResponse {
  string registration_id = 1;
}

message VerifyEmailRequest {
  string token = 1;
}

message VerifyEmailResponse {}

message AuthenticateWithPasswordRequest {
  string email = 1;
  string password = 2;
}

message RefreshAuthenticationRequest {
  string refresh_token = 1;
}

message AuthenticationSession {
  string access_token = 1;
  google.protobuf.Timestamp access_token_expiration_date = 2;
  string refresh_token = 3;
  google.protobuf.Timestamp refresh_token_expiration_date = 4;
}
